language: rust
os:
  - linux
  - osx
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - CARGOFLAGS=--no-default-features
  - CARGOFLAGS=--no-default-features --features std
  - CARGOFLAGS=--no-default-features --features runtime_select
  - CARGOFLAGS=--no-default-features --features runtime_select,std
script:
  - RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=full cargo test --verbose $CARGOFLAGS
