language: rust
os:
  - linux
  - osx
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - env: CARGOFLAGS=
    - env: CARGOFLAGS=--no-default-features
    - env: CARGOFLAGS=--no-default-features --features std
    - env: CARGOFLAGS=--no-default-features --features runtime_select
    - env: CARGOFLAGS=--no-default-features --features runtime_select,std
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=full cargo test --verbose $CARGOFLAGS
