[package]
name = "t1ha"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[lib]
bench = false

[features]
default = []
unaligned_access = []

[dependencies]

[dependencies.num-traits]
version = "0.2"
default-features = false

[dev-dependencies]
criterion = "0.2"
lazy_static = "1.3"

[build-dependencies]
rustc_version = "0.2"

[[bench]]
name = "t1ha0"
harness = false
