[package]
name = "rust-t1ha"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[features]
default = []
unaligned_access = []

[dependencies]

[dependencies.num-traits]
version = "0.2"
default-features = false

[build-dependencies]
rustc_version = "0.2"
